// GENERADO por tools/design-tokens desde packages/design/*.json. No editar: ejecuta `make tokens`.

/** Referencias a variables CSS: úsalas en estilos para respetar el tema claro/oscuro. */
export const color = {
  accent: "var(--rp-color-accent)",
  accentFill: "var(--rp-color-accent-fill)",
  accentSoft: "var(--rp-color-accent-soft)",
  background: "var(--rp-color-background)",
  bar: "var(--rp-color-bar)",
  dangerFill: "var(--rp-color-danger-fill)",
  dangerSoft: "var(--rp-color-danger-soft)",
  dangerText: "var(--rp-color-danger-text)",
  fill: "var(--rp-color-fill)",
  fillSubtle: "var(--rp-color-fill-subtle)",
  label: "var(--rp-color-label)",
  labelSecondary: "var(--rp-color-label-secondary)",
  labelTertiary: "var(--rp-color-label-tertiary)",
  onAccent: "var(--rp-color-on-accent)",
  onDanger: "var(--rp-color-on-danger)",
  scrim: "var(--rp-color-scrim)",
  separator: "var(--rp-color-separator)",
  successSoft: "var(--rp-color-success-soft)",
  successText: "var(--rp-color-success-text)",
  surface: "var(--rp-color-surface)",
  surfaceRaised: "var(--rp-color-surface-raised)",
  switchOn: "var(--rp-color-switch-on)",
  warningSoft: "var(--rp-color-warning-soft)",
  warningText: "var(--rp-color-warning-text)",
} as const;

export const tint = {
  blue: "var(--rp-tint-blue)",
  gray: "var(--rp-tint-gray)",
  green: "var(--rp-tint-green)",
  indigo: "var(--rp-tint-indigo)",
  orange: "var(--rp-tint-orange)",
  pink: "var(--rp-tint-pink)",
  purple: "var(--rp-tint-purple)",
  red: "var(--rp-tint-red)",
  teal: "var(--rp-tint-teal)",
  yellow: "var(--rp-tint-yellow)",
} as const;

/** Estados de mesa (RF-03-02): fondo, texto e icono semántico. */
export const mesa = {
  bloqueada: { bg: "var(--rp-mesa-bloqueada-bg)", fg: "var(--rp-mesa-bloqueada-fg)", icon: "bloqueo" },
  demorada: { bg: "var(--rp-mesa-demorada-bg)", fg: "var(--rp-mesa-demorada-fg)", icon: "tiempo" },
  libre: { bg: "var(--rp-mesa-libre-bg)", fg: "var(--rp-mesa-libre-fg)", icon: "libre" },
  ocupada: { bg: "var(--rp-mesa-ocupada-bg)", fg: "var(--rp-mesa-ocupada-fg)", icon: "ocupada" },
  porPagar: { bg: "var(--rp-mesa-por-pagar-bg)", fg: "var(--rp-mesa-por-pagar-fg)", icon: "factura" },
} as const;

export type EstadoMesa = keyof typeof mesa;
export type Tint = keyof typeof tint;

/** Valores crudos por tema, para canvas, gráficos o correos donde no hay variables CSS. */
export const raw = {
  color: {
    accent: { light: "#0066CC", dark: "#409CFF" },
    accentFill: { light: "#0066CC", dark: "#0071E3" },
    accentSoft: { light: "#E5F0FB", dark: "#10283F" },
    background: { light: "#F2F2F7", dark: "#000000" },
    bar: { light: "rgba(249,249,249,0.8)", dark: "rgba(22,22,24,0.74)" },
    dangerFill: { light: "#D70015", dark: "#D70015" },
    dangerSoft: { light: "#FDE8EA", dark: "#3F1B1B" },
    dangerText: { light: "#D70015", dark: "#FF6961" },
    fill: { light: "rgba(118,118,128,0.12)", dark: "rgba(120,120,128,0.24)" },
    fillSubtle: { light: "rgba(118,118,128,0.08)", dark: "rgba(120,120,128,0.16)" },
    label: { light: "#000000", dark: "#FFFFFF" },
    labelSecondary: { light: "#636366", dark: "#AEAEB2" },
    labelTertiary: { light: "#AEAEB2", dark: "#636366" },
    onAccent: { light: "#FFFFFF", dark: "#FFFFFF" },
    onDanger: { light: "#FFFFFF", dark: "#FFFFFF" },
    scrim: { light: "rgba(0,0,0,0.28)", dark: "rgba(0,0,0,0.55)" },
    separator: { light: "rgba(60,60,67,0.29)", dark: "rgba(84,84,88,0.6)" },
    successSoft: { light: "#E6F6EA", dark: "#173D22" },
    successText: { light: "#1B7A33", dark: "#30D158" },
    surface: { light: "#FFFFFF", dark: "#1C1C1E" },
    surfaceRaised: { light: "#FFFFFF", dark: "#2C2C2E" },
    switchOn: { light: "#34C759", dark: "#30D158" },
    warningSoft: { light: "#FFF1E0", dark: "#3D2C12" },
    warningText: { light: "#B34700", dark: "#FF9F0A" },
  },
  tint: {
    blue: { light: "#007AFF", dark: "#0A84FF" },
    gray: { light: "#8E8E93", dark: "#98989D" },
    green: { light: "#34C759", dark: "#30D158" },
    indigo: { light: "#5856D6", dark: "#5E5CE6" },
    orange: { light: "#FF9500", dark: "#FF9F0A" },
    pink: { light: "#FF2D55", dark: "#FF375F" },
    purple: { light: "#AF52DE", dark: "#BF5AF2" },
    red: { light: "#FF3B30", dark: "#FF453A" },
    teal: { light: "#30B0C7", dark: "#40C8E0" },
    yellow: { light: "#FFCC00", dark: "#FFD60A" },
  },
} as const;

export const text = {
  amount: { size: 48, line: 52, weight: 700, tracking: -0.03 },
  body: { size: 17, line: 22, weight: 400, tracking: -0.024 },
  callout: { size: 16, line: 21, weight: 400, tracking: -0.019 },
  caption1: { size: 12, line: 16, weight: 400, tracking: 0 },
  caption2: { size: 11, line: 13, weight: 400, tracking: 0.006 },
  footnote: { size: 13, line: 18, weight: 400, tracking: -0.005 },
  headline: { size: 17, line: 22, weight: 600, tracking: -0.024 },
  largeTitle: { size: 34, line: 41, weight: 700, tracking: -0.022 },
  subhead: { size: 15, line: 20, weight: 400, tracking: -0.014 },
  title1: { size: 28, line: 34, weight: 700, tracking: -0.021 },
  title2: { size: 22, line: 28, weight: 700, tracking: -0.016 },
  title3: { size: 20, line: 25, weight: 600, tracking: -0.017 },
} as const;

export const space = { "0": 0, "1": 4, "2": 8, "3": 12, "4": 16, "5": 20, "6": 24, "8": 32, "10": 40, "12": 48, } as const;
export const radius = { lg: 12, md: 10, phone: 44, pill: 999, sm: 8, widget: 22, xl: 14, xs: 6, } as const;
export const size = { appIcon: 60, cellMin: 52, keypadKey: 76, navBar: 52, tabBar: 56, touchMin: 48, } as const;

/** Iconos semánticos → nombre de Lucide (web). Nunca uses un nombre de Lucide directo en una pantalla. */
export const icons = {
  advertencia: "triangle-alert",
  agregar: "plus",
  ajustes: "settings",
  anulacion: "scissors",
  avisos: "bell",
  bar: "wine",
  bloqueo: "lock",
  buscar: "search",
  caja: "banknote",
  cajon: "archive",
  chevron: "chevron-right",
  cliente: "user",
  cocina: "flame",
  cocinaFria: "snowflake",
  cortesia: "gift",
  descuento: "tag",
  editar: "pencil",
  efectivo: "banknote",
  eliminar: "trash-2",
  enLinea: "wifi",
  error: "circle-alert",
  exito: "circle-check",
  factura: "receipt",
  impresora: "printer",
  inventario: "package",
  kds: "monitor",
  libre: "circle",
  ocupada: "utensils",
  orden: "clipboard-list",
  personal: "users",
  platoListo: "chef-hat",
  qr: "qr-code",
  reportes: "chart-column",
  salon: "layout-grid",
  sinInternet: "wifi-off",
  sinNodo: "server-off",
  sync: "refresh-cw",
  tarjeta: "credit-card",
  tiempo: "clock",
  transferencia: "smartphone",
} as const;

/** Color de fondo del mosaico de cada icono (estilo icono de app de iOS). */
export const iconTint: Record<IconName, Tint> = {
  advertencia: "orange",
  agregar: "blue",
  ajustes: "gray",
  anulacion: "red",
  avisos: "red",
  bar: "purple",
  bloqueo: "gray",
  buscar: "gray",
  caja: "green",
  cajon: "gray",
  chevron: "gray",
  cliente: "blue",
  cocina: "red",
  cocinaFria: "teal",
  cortesia: "pink",
  descuento: "orange",
  editar: "blue",
  efectivo: "green",
  eliminar: "red",
  enLinea: "green",
  error: "red",
  exito: "green",
  factura: "pink",
  impresora: "gray",
  inventario: "orange",
  kds: "indigo",
  libre: "green",
  ocupada: "yellow",
  orden: "orange",
  personal: "indigo",
  platoListo: "green",
  qr: "gray",
  reportes: "teal",
  salon: "blue",
  sinInternet: "orange",
  sinNodo: "red",
  sync: "blue",
  tarjeta: "blue",
  tiempo: "orange",
  transferencia: "purple",
};

export type IconName = keyof typeof icons;
